{"name": "Login with invalid parameters", "status": "broken", "statusDetails": {"message": "AttributeError: module 'allure' has no attribute 'attach'\n", "trace": "  File \"C:\\Users\\USER\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\USER\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\loginSteps.py\", line 100, in step_impl\n    allure.attach(context.driver.get_screenshot_as_png(), name=\"User must succesfully login to the Dashboard page\", attachment_type=AttachmentType.PNG)\n    ^^^^^^^^^^^^^\n"}, "steps": [{"name": "Given I Launch the browser", "status": "passed", "start": 1710977011087, "stop": 1710977014788}, {"name": "When I open orange HRM LoginPage", "status": "passed", "start": 1710977014788, "stop": 1710977015339}, {"name": "And Enter wrong password username \"admin\" and password \"admin\"", "status": "passed", "start": 1710977015339, "stop": 1710977015409}, {"name": "And Click on login button", "status": "passed", "start": 1710977015409, "stop": 1710977016412}, {"name": "Then Show message the Invalid credentials", "status": "broken", "statusDetails": {"message": "AttributeError: module 'allure' has no attribute 'attach'\n", "trace": "  File \"C:\\Users\\USER\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\USER\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\loginSteps.py\", line 100, in step_impl\n    allure.attach(context.driver.get_screenshot_as_png(), name=\"User must succesfully login to the Dashboard page\", attachment_type=AttachmentType.PNG)\n    ^^^^^^^^^^^^^\n"}, "start": 1710977016412, "stop": 1710977016938}], "start": 1710977011086, "stop": 1710977016939, "uuid": "584e1761-a1e1-44da-962c-a65e4becf022", "historyId": "d5e8681c802ec665563eb1960aa07645", "fullName": ": Login with invalid parameters", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}